version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user_mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'
    volumes:
      - my-db:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  my-db: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
