version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: 'mysql_ecom'
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user_mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'

    volumes:
      - my-db:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  my-db: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
